### ISSUE TITLE
配置完成後無法正常加載

### ISSUE THREAD

**Issue by dz-paji** [printempw/hexo-view-counter#1]
![image](https://user-images.githubusercontent.com/19299425/36143184-5bcd7680-10e5-11e8-94d5-c819044926d2.png)
在按照README搭建好之後 并在主題処進行了相應的修改，可是一直提示404 not found
![image](https://user-images.githubusercontent.com/19299425/36143256-8ce5e4aa-10e5-11e8-911e-ec617ba56287.png)
手動訪問的結果

**Comment by prinsss** [comment]
感谢反馈，这是 BUG（话说还真有除我以外的人用这玩意啊，惊了）

出错原因是你的 slug 中含有 `/` 斜杠符号，导致Lumen 路由出错了。等下我晚上 fix 一下。

**Comment by dz-paji** [comment]
吼的

Sent from HonokaMail by HonokaClub

On 13 Feb 2018, at 6:18 PM, 621sama <notifications@github.com<mailto:notifications@github.com>> wrote:


感谢反馈，这是 BUG（话说还真有除我以外的人用这玩意啊，惊了）

出错原因是你的 slug 中含有 / 斜杠符号，导致Lumen 路由出错了。等下我晚上 fix 一下。

**Comment by prinsss** [comment]
已修复。

（其实我都打算弃用这玩意了，改用 FaaS 之类的函数计算平台）

**Comment by dz-paji** [comment]
![image](https://user-images.githubusercontent.com/19299425/36147650-fa6da414-10f3-11e8-8042-17c88ed00fff.png)
emm 訪問increasing目錄會出現500錯誤

**Comment by prinsss** [comment]
`POST`，路由定义上没有允许 `GET` 访问（见 README）。你也可以在 `app/routes.php` 里自行修改。

**Comment by dz-paji** [comment]
![image](https://user-images.githubusercontent.com/19299425/36147763-7809489c-10f4-11e8-996c-ee675170ff78.png)
hmmm 我去訪問是因爲chrome這裏也有個500

**Comment by prinsss** [comment]
打开 F12 的 Network 选项卡，然后刷新，点那几个 500 的请求看响应。

![Snipaste_2018-02-13_19-33-41.png](https://i.loli.net/2018/02/13/5a82cd24b230c.png)

**Comment by prinsss** [comment]
如果响应是空的，那就看看 `storage/logs/lumen.log` 里有什么新报错没有。

**Comment by dz-paji** [comment]
相应是空的，但是并没有什么新报错
在删除```lumen.log```并重启webserver后甚至不能生成新的log文件

**Comment by prinsss** [comment]
很奇怪，可以排除 文件权限问题 吗？

**Comment by dz-paji** [comment]
hmmm 是文件权限的问题 给所有文件上了777就ok了

**Comment by dz-paji** [comment]
但如果都用777未免不太安全…… 不知道有哪几个文件是需要特殊权限的？

**Comment by prinsss** [comment]
`chown -R www ./`，在项目根目录下运行，www 改成你运行 web server 的用户。

**Comment by dz-paji** [comment]
好的 蟹蟹x
